// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"cleanArch/internal/repository/mongo"
	"cleanArch/internal/resolver"
	"cleanArch/internal/server"
	"cleanArch/internal/service/service"
	"cleanArch/pkg/logger"
	"cleanArch/pkg/mongodb"
	"context"
)

// Injectors from wire.go:

func InitializeApplication(ctx context.Context) (Application, error) {
	loggerLogger := logger.NewLogger()
	database, err := mongodb.NewMongoDB(ctx, loggerLogger)
	if err != nil {
		return Application{}, err
	}
	user := mongo.NewUserRepo(database)
	serviceUser := service.NewUserService(user, loggerLogger)
	resolverResolver := resolver.NewResolver(serviceUser, loggerLogger)
	mux := server.NewRouter(resolverResolver)
	httpServer := server.NewHttpServer(mux)
	application := newApplication(httpServer)
	return application, nil
}
